### ISSUE TITLE
Exception if a certificate specifies multiple CNs

### ISSUE THREAD

**Issue by hardoverflow** [Icinga/icingaweb2-module-x509#9] opened 2018-11-28 10:33 UTC
## Expected Behavior
The scan should go through without an error message.

## Current Behavior
We always get the following error message when we start the scan job (see below). After scan, the graph for "Certificates by duration" is gray with no stats.

## Steps to Reproduce (for bugs)
1. Initialize fresh x509 database
2. ```icingacli x509 scan --job XYZ```

## Your Environment

* Module version (System - About):
* Icinga Web 2 version: 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* Operating System and version: CentOS 7 3.10.0-862.14.4.el7.x86_64
* Webserver, PHP versions: httpd/2.4.6. / PHP 7.1.8 (scl)

## Error message
```
[root@XYZ userXYZ]# icingacli x509 scan --job XYZ
Array to string conversion
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Array to string...', '/usr/share/icin...', 315, Array)
#1 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(315): PDOStatement->execute(Array)
#2 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(351): ipl\Sql\Connection->prepexec('INSERT INTO x50...')
#3 /usr/share/icingaweb2/modules/x509/library/X509/CertificateUtils.php(246): ipl\Sql\Connection->insert('x509_certificat...', Array)
#4 /usr/share/icingaweb2/modules/x509/library/X509/Job.php(240): Icinga\Module\X509\CertificateUtils::findOrInsertCert(Object(ipl\Sql\Connection), Resource id #4510, Array)
#5 [internal function]: Icinga\Module\X509\Job->Icinga\Module\X509\{closure}(Object(ipl\Sql\Connection))
#6 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(452): call_user_func(Object(Closure), Object(ipl\Sql\Connection))
#7 /usr/share/icingaweb2/modules/x509/library/X509/Job.php(251): ipl\Sql\Connection->transaction(Object(Closure))
#8 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(25): Icinga\Module\X509\Job->Icinga\Module\X509\{closure}(Object(React\Socket\Connection))
#9 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#10 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#11 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#12 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#13 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#14 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#15 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#16 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise-timer/src/functions.php(31): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#17 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(25): React\Promise\Timer\{closure}(Object(React\Socket\Connection))
#18 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#19 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#20 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#21 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(25): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#22 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#23 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#24 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#25 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#26 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure))
#27 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#28 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#29 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#30 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#31 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#32 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#33 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#34 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#35 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#36 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#37 [internal function]: React\Promise\Promise::React\Promise\{closure}(NULL)
#38 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Deferred.php(36): call_user_func(Object(Closure), NULL)
#39 /usr/share/icingaweb2/modules/reactbundle/vendor/react/socket/src/StreamEncryption.php(137): React\Promise\Deferred->resolve()
#40 /usr/share/icingaweb2/modules/reactbundle/vendor/react/socket/src/StreamEncryption.php(95): React\Socket\StreamEncryption->toggleCrypto(Resource id #4342, Object(React\Promise\Deferred), true, 57)
#41 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(238): React\Socket\StreamEncryption->React\Socket\{closure}(Resource id #4342)
#42 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(205): React\EventLoop\StreamSelectLoop->waitForStreamActivity(2724533)
#43 /usr/share/icingaweb2/modules/x509/library/X509/Job.php(311): React\EventLoop\StreamSelectLoop->run()
#44 /usr/share/icingaweb2/modules/x509/application/clicommands/ScanCommand.php(51): Icinga\Module\X509\Job->run()
#45 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\X509\Clicommands\ScanCommand->indexAction()
#46 /usr/share/php/Icinga/Application/Cli.php(149): Icinga\Cli\Loader->dispatch()
#47 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#48 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#49 {main}
```

**Comment by lippserd** [comment] 2018-11-29 11:49
Hi,

Thanks for the report. If you execute the scan command with `--trace` appended, you should see the actual function call arguments in detail. Please have a look at the first array which looks like this:

```
array (
    0 => 'ACCVRAIZ1',
    1 => 'binary stuff',
    2 => 'ACCVRAIZ1',
    3 => 'binary stuff',
    4 => 3,
    5 => 'yes',
    6 => 'yes',
    7 => 'RSA',
    8 => 4096,
    9 => 'RSA',
    10 => 'SHA1',
    11 => 1304588257,
    12 => 1924940257,
    13 => 'binary stuff',
    14 => 'binary stuff',
```

This is the certificate information which is about to be stored into the database. Please note that in this example all values are either strings or integers.

In your case, you should have a line which looks like this:

```
 
$number  => array (
      0 => 'RSA',
      1 => 'SHA1',
    ),
```
If you find something like that, could please tell me the $number?

I hope this makes some sense to you.

Best,
Eric

**Comment by hardoverflow** [comment] 2018-11-30 06:49
I added the ```--trace``` and the ```--debug``` switch, but the result is the same. No additional trace data available.

**Comment by lippserd** [comment] 2018-11-30 11:41
That is odd. Could you please share the output of `php -i`? In addition, could you please checkout the related PR and rerun the command? It should now show the certificate info which is failing. If you have a git installation, you may run `git fetch && git checkout -b fix/scan-job-array-to-string-conversion origin/fix/scan-job-array-to-string-conversion` to checkout the PR.

**Comment by lippserd** [comment] 2018-11-30 12:34
Just to be sure, is subject the only key which has an array as its value?

**Comment by lippserd** [comment] 2018-11-30 12:35
It looks like your certificate has multiple CNs in its subject. Is that true?

**Comment by hardoverflow** [comment] 2018-11-30 12:37
> 
> 
> It looks like your certificate has multiple CNs in its subject. Is that true?

Yes, that is true.

**Comment by lippserd** [comment] 2018-11-30 12:55
Could you please run `git pull` and test again?

**Comment by hardoverflow** [comment] 2018-12-03 08:46
```
git pull # fix/scan-job-array-to-string-conversion
icingacli x509 scan --job XYZ
```

Now there is no error with the ```--trace``` switch, but the graph for "Certificates by duration" is already grayed out with no stats.

**Comment by lippserd** [comment] 2018-12-04 14:59
@hardoverflow @gribnut Could you please share the output of `php -i`. Because the `--trace` option really should show the actual function call arguments. Which OS are you running?

Multiple CNs are not allowed as far as I know. But hey, the module should not fail in this case. I'll just pick the first found CN.

@hardoverflow Did the scan job import any certificate? Is everything greyed out? Do you have items beneath certificates and/or usage? The duration donut ignores CAs. So if you have only CAs in your env, you won't see that donut colorful.

**Comment by gribnut** [comment] 2018-12-04 17:41
Running CentOS 7.5 and PHP v 7.1.8.  Attached file of output for `php -i`:
[php_info.txt](https://github.com/Icinga/icingaweb2-module-x509/files/2645157/php_info.txt)

**Comment by hardoverflow** [comment] 2018-12-05 07:14
![grafik](https://user-images.githubusercontent.com/4113231/49496260-ba8d2e00-f865-11e8-893a-0adb7835f200.png)

Output from: ```php -i```
[php.txt](https://github.com/Icinga/icingaweb2-module-x509/files/2647570/php.txt)

**Comment by lippserd** [comment] 2018-12-10 12:10
@hardoverflow Could you please execute the following SQL query?

```sql
SELECT COUNT(*) FROM x509_certificate WHERE ca = 'no';
```

This lists the number of non-CA certs. Plus, could you please retest the PR? I forced the branch. You may run `git fetch && git reset --hard origin/HEAD` in order to checkout the latest changes.

**Comment by lippserd** [comment] 2018-12-10 12:11
And thanks for the PHP infos guys. I'll have a look at them.

**Comment by hardoverflow** [comment] 2018-12-18 08:51
@lippserd Result: 353

**Comment by nilmerg** [comment] 2019-03-28 09:49
@hardoverflow Do you still have an empty duration graph?

I just tried to reproduce this, even by simulating varying results the database may produce. Without any luck, though. So, if you still have this problem, you may consider dropping the database and starting from scratch. This should clear any oddities the previous (failing) scans may have produced.

I'll close this issue for now, the multiple CN issue is solved. If the empty duration graph comes back, please open a new issue.

**Closed by nilmerg** 2019-03-28 09:49 UTC
Labels: bug
