### ISSUE TITLE
 Invalid UTF-8 on row <host>, column host_ip: " dd" (0x0000000000000000000000000a64649e)

### ISSUE THREAD

**Issue by stultitiophobia** [Icinga/icingaweb2-module-x509#173] opened 2023-04-12 21:09 UTC
After a module update to 1.2.0 I get the following error in director -> automation -> import

Invalid UTF-8 on row <host>, column host_ip: " dd" (0x0000000000000000000000000a64649e)

<img width="640" alt="image" src="https://user-images.githubusercontent.com/809290/231584966-d44a1a6c-315e-4b29-b216-aec1567adf9f.png">

also the preview of the modificatory does not to be correct ...

<img width="842" alt="image" src="https://user-images.githubusercontent.com/809290/231584714-70c316b4-03a3-4611-ba3e-e464fb510521.png">

I configured the x509 module as described in the manual.

## Environment

* Icinga Web 2 version and modules (System - About):
2.11.4
* Web browser used:
Safari / Brave
* Icinga 2 version used (`icinga2 --version`):
r2.13.7-1
* PHP version used (`php --version`):
7.4.3
* Server operating system and version:
Ubuntu 20.04.6 LTS

**Comment by stultitiophobia** [comment] 2023-04-12 21:43
The mariadb entries in the x509_target table look like this (if this helps):
<img width="471" alt="image" src="https://user-images.githubusercontent.com/809290/231592683-6fd322fe-9237-4074-9f11-57a01f72b7a8.png">

**Comment by stultitiophobia** [comment] 2023-04-12 21:44
<img width="560" alt="image" src="https://user-images.githubusercontent.com/809290/231592789-f6fdc6a3-af79-4251-baa2-5dc51fcc112c.png">

**Comment by yhabteab** [comment] 2023-04-13 06:41
Duplicate of https://github.com/Icinga/icingaweb2-module-x509/issues/172

**Closed by yhabteab** 2023-04-13 06:41 UTC
