### ISSUE TITLE
Scan Job creates duplicate entrys

### ISSUE THREAD

**Issue by GalipoliX** [Icinga/icingaweb2-module-x509#177] opened 2023-05-08 08:40 UTC
Hello!
for every Scan job that is running a new entry in the database under x509_target and x509_dn is created.
Its not updating previous entrys. Every Scan is a new target.
![image](https://user-images.githubusercontent.com/26061395/236775449-c35167a2-2c2c-46a0-ab8b-b9a9967a5a82.png)

They then show up multiple times in the webUI
![image](https://user-images.githubusercontent.com/26061395/236775839-875f9e81-4eb0-46e2-87a8-48041d66bcd9.png)

This is blowing up the database massively.

I had one simple Scan job running over night every minute, and now have 4248 entrys in x509_target, which should be around 40.

To reproduce the issue i installed a new Server with a completely new and empty database.
The only thing i did after installing is importing our own CA using the import command and created one simple scan job.
No SNI definitions, etc.
It makes no difference if i run the scan by daemon or manualy.

Environment:
Ubuntu Server                 22.02.2
Icinga Web 2 Version	2.11.4
PHP Version	                8.1.2-1ubuntu2.11
MariaDB                          15.1
icingadb		                1.0.2
x509		                1.2.1

All installed from official repository.

Hope this can be solved!

Best regards

**Comment by yhabteab** [comment] 2023-05-08 09:02
Hii @GalipoliX, thanks for reporting. This is unfortunately caused by the same bug as https://github.com/Icinga/icingaweb2-module-x509/issues/172. You can use the patch from https://github.com/Icinga/icingaweb2-module-x509/issues/172#issuecomment-1505377115 to temporarily fix your issue.

**Comment by yhabteab** [comment] 2023-05-08 09:02
Duplicate of https://github.com/Icinga/icingaweb2-module-x509/issues/172

**Closed by yhabteab** 2023-05-08 09:02 UTC
Labels: bug

**Comment by GalipoliX** [comment] 2023-05-08 12:46
Looks Good!
Thanks for the quick response!
