### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in CheckCommand.php

### ISSUE THREAD

**Issue by svenluzar** [Icinga/icingaweb2-module-x509#133] opened 2022-10-19 10:13 UTC
## Describe the bug

The check crashes with the following stack trace:
```
PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /usr/share/icingaweb2/modules/x509/application/clicommands/CheckCommand.php:145
Stack trace:
#0 /usr/share/php/Icinga/Cli/Loader.php(267): Icinga\Module\X509\Clicommands\CheckCommand->hostAction()
#1 /usr/share/php/Icinga/Application/Cli.php(164): Icinga\Cli\Loader->dispatch()
#2 /usr/share/php/Icinga/Application/Cli.php(154): Icinga\Application\Cli->dispatchOnce()
#3 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#4 {main}
  thrown in /usr/share/icingaweb2/modules/x509/application/clicommands/CheckCommand.php on line XXX

XXX = several numbers in the class CheckCommand.php
```

## To Reproduce

1. Use the docker container jordan/icinga2:2.13.5
2. git clone https://github.com/Icinga/icingaweb2-module-x509.git
3. mv /usr/share/icingaweb2/modules/icingaweb2-module-x509 /usr/share/icingaweb2/modules/x509
4. chown -R www-data:icingaweb2 /usr/share/icingaweb2/modules/x509/

## Expected behavior
No crash

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.10.1
* Web browser used: Chrome Version 106.0.5249.119 (x86_64)
* Icinga 2 version used (`icinga2 --version`): r2.13.3-1
* PHP version used (`php --version`): PHP 7.4.28
* Server operating system and version: Debian GNU/Linux 11

**Comment by yhabteab** [comment] 2022-10-19 12:38
Hii, thanks for reporting and the patching obviously :).

It's caused by this [change](https://github.com/Icinga/icingaweb2-module-x509/pull/124) and forgot to adjust cli commands as well 🙈

**Comment by yhabteab** [comment] 2023-02-02 10:14
Fixed by https://github.com/Icinga/icingaweb2-module-x509/pull/130

**Closed by yhabteab** 2023-02-02 10:14 UTC
Labels: bug
